name: addFriend
version: 1.0
main: org.pubdevz.addfriend.AddFriend
api-version: '1.20'
commands:
  addfriend:
    description: 친구 추가 명령어
    usage: "/addfriend <username>"
    aliases: ["addfriend"]
  listfriend:
    description: 친구 목록 명령어
    usage: "/listfriend"
    aliases: ["listfriend"]
  removefriend:
    description: 친구 추가 명령어
    usage: "/removefriend <username>"
    aliases: ["removefriend"]